version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/start.sh:/start.sh
    depends_on:
      - app
    networks:
      - fullcycle

  app:
    build: ./node
    container_name: app
    volumes:
      - ./node:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=fullcycle
    depends_on:
      - db
    networks:
      - fullcycle

  db:
    image: mysql:8
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle
    ports:
      - '3306:3306'
    networks:
      - fullcycle

networks:
  fullcycle:
    driver: bridge
