version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/start.sh:/start.sh
    depends_on:
      - app
    networks:
      - fullcycle

  app:
    build: ./node
    container_name: app
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    working_dir: /usr/src/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=fullcycle
    depends_on:
      - db
    entrypoint:
      [
        'dockerize',
        '-wait',
        'tcp://db:3306',
        '-timeout',
        '60s',
        'node',
        'server.js',
      ]
    networks:
      - fullcycle

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fullcycle
    restart: always

networks:
  fullcycle:
    driver: bridge

volumes:
  mysql_data:
